apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckywebapp
  labels:
    app: luckywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckywebapp
  template:
    metadata:
      labels:
        app: luckywebapp
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: luckywebapp
        image: ravi5291.azurecr.io/my-app-image:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: luckywebapp-service
spec:
  type: LoadBalancer
  selector:
    app: luckywebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
git add jenkinsfile k8s/petclinic.yml
git commit -m "Add Jenkins pipeline and Kubernetes deployment files"
git push
